/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencvproject_NdkUtils */

#ifndef _Included_com_example_opencvproject_NdkUtils
#define _Included_com_example_opencvproject_NdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opencvproject_NdkUtils
 * Method:    filter
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_opencvproject_NdkUtils_filter
  (JNIEnv *, jclass, jintArray, jint, jint,jint,jint);

#ifdef __cplusplus
}
#endif
#endif
